### PR TITLE
update API steemit

### PR DESCRIPTION
**Pull request by developerfred**
### API  GET LIST
#2 

#### get_discussion
- [x] get_discussion 
- [x] get_discussions_by_active 
- [x] get_discussions_by_author_before_date 
- [x] get_discussions_by_blog 
- [x] get_discussions_by_cashout 
- [x] get_discussions_by_children 
- [x] get_discussions_by_comments 
- [x] get_discussions_by_created 
- [x] get_discussions_by_feed 
- [x] get_discussions_by_hot 
- [x] get_discussions_by_promoted 
- [x] get_discussions_by_trending 
- [x] get_discussions_by_votes 
- [x] get_post_discussions_by_payout 
- [x] get_replies_by_last_update 
- [x] get_tags_used_by_author 
- [x] get_trending_tags

### get_account
- [x] get_account_bandwidth 
- [x] get_account_count 
- [x] get_account_history 
- [x] get_account_reputations 
- [x] get_account_votes 
- [x] get_accounts 
### get_active
- [x] get_active_votes 
- [x] get_active_witnesses 
- [x] get_block 
- [x] get_block_header 
#### get_blog
- [x] get_blog 
- [x] get_blog_authors 
- [x] get_blog_entries 
- [x] get_chain_properties 
- [x] get_comment_discussions_by_payout 
- [x] get_config 
#### get_content
- [x] get_content 
- [x] get_content_replies 
- [x] get_conversion_requests 
- [x] get_current_median_history_price 
- [x] get_dynamic_global_properties
- [x] get_escrow
- [x] get_expiring_vesting_delegations
- [x] get_feed
- [x] get_feed_entries
- [x] get_feed_history
- [x] get_follow_count
- [x] get_followers
- [x] get_following

- [x] get_hardfork_version
- [x] get_key_references
- [x] get_market_history
- [x] get_market_history_buckets
- [x] get_next_scheduled_hardfork
- [x] get_open_orders
- [x] get_ops_in_block
- [x] get_order_book
- [x] get_owner_history
- [x] get_post_discussions_by_payout
- [x] get_potential_signatures
- [x] get_reblogged_by
- [x] get_recent_trades
- [x] get_recovery_request
- [x] get_replies_by_last_update
- [x] get_required_signatures
- [x] get_reward_fund
- [x] get_savings_withdraw_from
- [x] get_savings_withdraw_to
- [x] get_state
- [x] get_tags_used_by_author
- [x] get_ticker
- [x] get_trade_history
- [x] get_transaction

- [x] get_transaction_hex
- [x] get_trending_tags
- [x] get_version
- [x] get_vesting_delegations
- [x] get_volume
- [x] get_withdraw_routes
### Get_witness
- [x] get_witness_by_account
- [x] get_witness_count
- [x] get_witness_schedule
- [x] get_witnesses
- [x] get_witnesses_by_vote

### CODE REVIEW

**Comment by feruzm** [comment]
Thank you for your contribution and PR, please add your Steem username here as well.
Have you tested all APIs after adding? I will test it out over the weekend! 👍

**Comment by developerfred** [comment]
I tested it, but it would be good to test it again. my user @developerfred.  

Thanks 👍

**Review by feruzm — CHANGES_REQUESTED** [review]
Great work so far! 👍 
Is it possible separate `tags` to these exact categories that way, it will be plugin consistent? You did start it by adding `Condenser` which I think very smart way to organize APIs.

Current tags are somewhat confusing because they don't follow steem plugin or api categories.
I realize it is bit outside scope of initial work, so willing to add 5000 ESTM extra on top of all rewards, looking forward for your comment...

steem api tags/plugins

ref: https://developers.steem.io/apidefinitions/#condenser_api.get_feed

**Comment by developerfred** [comment]
Of course, I'm going to update the API.

> Great work so far! 👍
> Is it possible separate `tags` to these exact categories that way, it will be plugin consistent? You did start it by adding `Condenser` which I think very smart way to organize APIs.
> 
> Current tags are somewhat confusing because they don't follow steem plugin or api categories.
> I realize it is bit outside scope of initial work, so willing to add 5000 ESTM extra on top of all rewards, looking forward for your comment...
> 
> steem api tags/plugins
> 
> ref: https://developers.steem.io/apidefinitions/#condenser_api.get_feed

Of course, I'm going to update the API.

**Comment by feruzm** [comment]
Great! Well done!

**Comment by feruzm** [comment]
Some parts are still remaining though, I now see that it was WIP commit, please submit remaining and we can close this task!

**Pull request merged**
